### ISSUE TITLE
shouldn't be a maxrow kind of option to read maximum rows ?

### ISSUE THREAD

**Issue by amitbravo** [DiegoZoracKy/convert-excel-to-json#27]
of course I can use array.slice or something to cut off first N elements however, defining within options would be great.

**Comment by DiegoZoracKy** [comment]
Hello @amitbravo,

Can you tell me more about how you came up with this idea. I'm assuming that the case wasn't a large file that this lib couldn't handle, because otherwise you wouldn't have the data to do your own slice.

Did you face a case where you had too many sheets to do your own slice? If that is the case, the sheets had different N elements to be kept in?

**Comment by DiegoZoracKy** [comment]
Closing this thread due to inactivity.

@amitbravo in case you want to discuss further, feel free to reopen it.
