### ISSUE TITLE
Convert Excel to JSON and Get real data type

### ISSUE THREAD

**Issue by broerjuang** [DiegoZoracKy/convert-excel-to-json#3]
Hi @DiegoZoracKy, 

Thanks for creating this package, but I have following issue when I want to convert value from JSON to real `JS` value. It always returns `string` instead of `number` for the value that supposed to be `number`. Is there any support for this? Thanks.

**Comment by DiegoZoracKy** [comment]
Hi @broerjuang,

Now it has support for it! From now the conversion will return `Number` when the cell is of that type. 

Improve the conversion in order to respect the data type of the cell (whenever is possible) was already on my plans, however I wasn't find time to improve it towards that. At least for now the case for `Number` is done.

Check the version 1.2.0 and tell me if it's ok.

Thanks;

**Comment by fpolowood** [comment]
@DiegoZoracKy wow... I created an app that extracts json from excel files and then uses json schemas to validate the content, since the excel files will be edited by users... but my validation was failing because of numbers coming in as strings... so I came here to create an issue... and voilá ... it is fixed!!!

**Comment by DiegoZoracKy** [comment]
@fpolowood Great! Just in time! Did you check the 1.2.0 version and now is it working for you?

**Comment by fpolowood** [comment]
Yes, thank you, it was fixed before I could enter the issue :) It is working great, the issue I am having now is that some phone numbers were entered as 9195551212 and they are now treated as numbers :) But we should be able to fix that at the spreadsheet. 
BTY, I am using ajv to validate the output and it is invaluable to catch inconsistencies before they get deployed. 

Many thanks.

**Comment by DiegoZoracKy** [comment]
@fpolowood One idea is to improve the API in order to give an option to force a data type (when possible) by column/key, with something like this:

```javascript
columnToKey: {
	A: 'id',
	B: 'name',
	C: {
		property: 'phoneNumber',
		dataType: 'String'
	}
}
```

And another one is to define a function to transform the data in some way. It would be used like this:

```javascript
columnToKey: {
	A: 'id',
	B: 'name',
	C: {
		property: 'phoneNumber',
		transform: (value, row) => value.toString() // 'row' would be the entire row with all its columns. To concatenate with values from other columns for example.
	}
}
```

In your case you can fix it on the spreadsheet, but having a scenario where one will receive spreadsheets from multiple sources, and the files would be going directly to the converter, it can be good to ensure the data transformation when configuring the engine.

And thanks for the tip about ajv.
